// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordResetToken struct {
	UserID    pgtype.UUID
	Token     pgtype.Text
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type ProviderToken struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Provider     string
	ProviderID   string
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamp
	ConnectedAt  pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Password  string
	Role      string
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
