// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProviderToken struct {
	ID           int32
	UserID       int32
	Provider     string
	ProviderID   string
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	TokenExpiry  pgtype.Timestamp
	ConnectedAt  pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     pgtype.Text
	Username  string
	Password  pgtype.Text
	Role      string
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
